version: '3'

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    networks:
      - node-network
    ports: 
      - "8080:80"
    tty: true
    container_name: nginx
    depends_on:
      - app
  app:
    build: 
      context: app
      dockerfile: Dockerfile
    networks:
      - node-network
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules #volume anonimo
    tty: true
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s node index.js
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./scripts/create.sql:/docker-entrypoint-initdb.d/1.sql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
networks:
  node-network:
    driver: bridge